version: 5.1.0
variant: default
logo: /img/CCSN.png
head:
    favicon: /img/CCSN.svg
    manifest:
        name: CCSN 
        short_name: CCSN
        start_url: https://ccsn.dev/
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: '/img/CCSN.png'
                sizes: ''
                type: 'image/png'
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/the-ccsn/the-ccsn.github.io
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
        No Derivatives:
            icon: fab fa-creative-commons-nd
            url: https://creativecommons.org/licenses/by-nd/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/the-ccsn/the-ccsn.github.io
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
        No Derivatives:
            icon: fab fa-creative-commons-nd
            url: https://creativecommons.org/licenses/by-nd/4.0/
search:
    type: insight
    index_pages: true
#comment:
#    type: disqus
#    shortname: ''
#donates:
#    -
#        type: afdian
#        url: ''
#    -
#        type: alipay
#        qrcode: ''
#    -
#        type: buymeacoffee
#        url: ''
#    -
#        type: patreon
#        url: ''
#    -
#        type: paypal
#        business: ''
#        currency_code: USD
#    -
#        type: wechat
#        qrcode: ''
share:
    type: sharethis
    install_url: 'https://ccsn.dev'
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: CCSN
        author_title: Changchen Students Network
        location: Beijing, China
        avatar: /img/CCSN.png
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/the-ccsn
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/the-ccsn
            Telegram:
                icon: fab fa-telegram
                url: https://t.me/theCCSN
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: left
        type: toc
        index: true
        collapsed: false
        depth: 3
    -
        position: left
        type: links
        links:
            Official Site: https://ccsn.dev/
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: false
    outdated_browser: true
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: loli
    fontcdn: ustc
    iconcdn: loli
